### ISSUE TITLE
Code Attribution

### ISSUE THREAD

**Issue by daodesigner** [HausDAO/daohaus-supergraph#18]
@skuhlmann, ya did me dirty on that initial "[fork](https://github.com/HausDAO/daohaus-supergraph/commit/3210682bbd7aeddf55ae6b459b0433e4737da7ad)" XD maybe you guys could put my github user on the readme (since you guys still use all my V2 mappings) <3 ?

It's not a big deal, but it feels bad to look back at this and see your name on the git blame for all my code.

**Comment by skuhlmann** [comment]
@daodesigner For sure. When moving to support the factories and moloch V1 and V2 we lost the git history. Very much my fault not to preserve that and lose attribution.

Not an excuse and 100% my mistake. I apologize wholeheartedly. Will get better attribution back in here.

**Comment by skuhlmann** [comment]
https://github.com/HausDAO/daohaus-supergraph/pull/20/files

**Comment by skuhlmann** [comment]
https://github.com/HausDAO/daohaus-supergraph/blob/master/README.md

**Comment by daodesigner** [comment]
💕💕💕
